name: CompiladorPruebador

on:
    push:
        branches:
            -main

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [12, 14, 16]
        steps:
            - name: Check code
              uses: actions/checkout@v2

            - name: setup nodejs ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                node-version: ${{ matrix.node-version }}
            
            - name: Install dependencies
              run: npm install
        
            - name: Run tests
              run: npm test
        