name: Docker con workflow

on:
   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Usar Action
      uses: ./actiondocker

    - name: Build
      uses: echo "Building..."

    - name: Test
      uses: echo "Tested"
