name: Docker con workflow

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Usar Action
      uses: ./actiondocker

    - name: Build
      run: echo "Building..."

    - name: Test
      run: echo "Tested"
