name: Ejecutar Scripts de la carpeta scripts

on:
    push:
    workflow_dispatch:

jobs:
    ejecutar-scripts-de-la-carpeta:
        runs-on: ubuntu-latest
        steps:
            - name:
              run: practicasgithub/scripts/script1.sh 

            - name:
              run: practicasgithub/scripts/script2.sh

            - name:
              run: practicasgithub/scripts/script3.sh