name: Ejecutar Scripts de la carpeta scripts

on:
    push:
    workflow_dispatch:

jobs:
    ejecutar-scripts-de-la-carpeta:
        runs-on: ubuntu-latest
        steps:
            - name: Clonar el repositorio 
              uses: actions/checkout@v4

            - name: Configurar Permisos
              run: chmod +x scripts/*.sh

            - name: ejecutar s1
              run: ./scripts/script1.sh 

            - name: ejecutar s2
              run: ./scripts/script2.sh

            - name: ejecutar s3
              run: ./scripts/script3.sh